# Generated by Django 5.1.6 on 2025-03-11 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
