# Generated by Django 5.1.6 on 2025-03-13 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0013_alter_shippingaddress_shipping_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='shipping_email',
            field=models.CharField(max_length=255),
        ),
    ]
