# Generated by Django 5.1.6 on 2025-03-14 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0015_alter_order_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveBigIntegerField(default=1),
        ),
    ]
