# Generated by Django 5.1.6 on 2025-03-24 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0018_order_date_shipped'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('date_ordered',)},
        ),
    ]
