# Generated by Django 5.1.6 on 2025-03-30 14:59

import django.core.validators
import ecommerseApp.common.custom_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0020_shippingaddress_shipping_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='shipping_phone',
            field=models.CharField(default=1, max_length=20, validators=[django.core.validators.MinLengthValidator(4, message='Phone number must be between 4 and 20 digits.'), ecommerseApp.common.custom_validators.validate_phone_number]),
            preserve_default=False,
        ),
    ]
