# Generated by Django 5.1.6 on 2025-04-28 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0022_order_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='options',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variant',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
