# Generated by Django 5.1.6 on 2025-04-28 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0023_orderitem_options_orderitem_variant'),
        ('store', '0022_productvariant_track_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='options',
            new_name='option_details',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variant_items', to='store.productvariant'),
        ),
    ]
