# Generated by Django 5.1.6 on 2025-03-03 08:17

import django.core.validators
import ecommerseApp.common.custom_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.MinLengthValidator(1, message='The length of the name must be between 1 and 50 characters.'), ecommerseApp.common.custom_validators.validate_lettres]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.MinLengthValidator(1, message='The length of the name must be between 1 and 50 characters.'), ecommerseApp.common.custom_validators.validate_lettres]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.MinLengthValidator(4, message='Phone number must be between 4 and 20 digits.'), ecommerseApp.common.custom_validators.validate_phone_number]),
        ),
    ]
