# Generated by Django 5.1.6 on 2025-03-10 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customer_address_customer_address2_customer_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='old_cart',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
