# Generated by Django 5.1.6 on 2025-03-10 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customer_old_cart'),
        ('store', '0007_order_address_order_product_order_quantity_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='Profile',
        ),
    ]
