# Generated by Django 5.1.6 on 2025-03-02 14:03

import django.core.validators
import ecommerseApp.common.custom_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.MinLengthValidator(4, message='Phone number must be between 4 and 20 digits.'), ecommerseApp.common.custom_validators.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price_at_time_of_order',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
