# Generated by Django 5.1.6 on 2025-03-11 05:18

import django.core.validators
import django.db.models.deletion
import ecommerseApp.common.custom_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_order_address_order_product_order_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.MinLengthValidator(1, message='The length of the name must be between 1 and 50 characters.'), ecommerseApp.common.custom_validators.validate_lettres])),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.MinLengthValidator(1, message='The length of the name must be between 1 and 50 characters.'), ecommerseApp.common.custom_validators.validate_lettres])),
                ('phone', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.MinLengthValidator(4, message='Phone number must be between 4 and 20 digits.'), ecommerseApp.common.custom_validators.validate_phone_number])),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='email',
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_order', to='store.customer'),
        ),
    ]
