# Generated by Django 5.1.6 on 2025-04-21 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_product_is_active_product_is_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
