# Generated by Django 5.1.6 on 2025-04-23 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_productoption_productoptionvalue_productvariant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='sku',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
