# Generated by Django 5.1.6 on 2025-05-06 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_alter_product_quantity_alter_product_track_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_options',
            field=models.BooleanField(default=False),
        ),
    ]
