# Generated by Django 5.1.6 on 2025-05-08 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_product_has_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(default=1, help_text='Stock Keeping Unit (unique)', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='sku',
            field=models.CharField(default=1, help_text='Stock Keeping Unit (unique)', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
